// Three-tier explanations for the Learn tab, keyed by concept.
// Each entry has three fields:
//   baby       - playful, analogy-driven, zero jargon
//   individual - plain, direct, confident, no jargon, no formulas
//   expert     - professional prose grounded in how CFA curriculum and
//                institutional risk literature actually frame the concept:
//                history, what it corrects for, where it's used in practice.
//                A formula may appear as a secondary reference, but the
//                paragraph itself has to do real explanatory work.
export const learnContent = {
  annual_return: {
    baby: "Imagine planting a money tree on January 1st. Annual Return is how much taller it grew by December 31st, told to you as a percentage, so a tiny tree and a giant tree can be compared fairly.",
    individual: "Annual Return measures how much your portfolio grew, or shrank, over a year, expressed as a percentage so portfolios of any size can be compared apples-to-apples. It's calculated as a compounded annual rate rather than a simple average, which matters because compounding is how money actually grows across multiple years.",
    expert: "Annualised return, more precisely the Compound Annual Growth Rate (CAGR), expresses a multi-period return as the constant annual rate that would produce the same cumulative result: (Ending Value / Starting Value)^(1/years) − 1. It's preferred over an arithmetic average of yearly returns because arithmetic averaging systematically overstates true growth when returns vary period to period — a portfolio that gains 50% then loses 50% has an arithmetic average of 0% but has actually lost 25% of its value. CAGR is the standard denominator for nearly every other risk-adjusted metric — Sharpe, Sortino, Treynor — because it isolates the growth rate from the noise of interim volatility, and it's the figure fund fact sheets and prospectuses are required to disclose under standardized performance presentation rules.",
  },

  volatility: {
    baby: "Volatility is how wiggly the road is. A smooth highway barely bounces you around. A bumpy dirt road throws you side to side, even if both roads end up at the same destination.",
    individual: "Volatility measures how much your portfolio's value swings up and down over time, regardless of direction. A high-volatility portfolio might jump 3% one day and drop 3% the next, even if it ends up in the same place a year later as a calmer portfolio. It's usually shown as an annualised percentage, so you can compare the \"bumpiness\" of different portfolios directly.",
    expert: "Volatility, formally the annualised standard deviation of returns, quantifies the dispersion of a return series around its mean. It's derived by computing the standard deviation of daily returns and scaling by the square root of time — typically √252 for a daily-to-annual conversion, a convention rooted in the assumption that returns are independently and identically distributed. Volatility is the foundational input to nearly all of modern portfolio theory: it's the denominator in the Sharpe ratio, the core variable in Black-Scholes option pricing, and the basis for Markowitz's mean-variance optimization. Its central limitation, debated in the risk literature for decades, is that it penalises upside and downside movement identically, treating a surprise rally the same as a crash — precisely the gap that downside-focused measures like Sortino and semi-deviation were built to close.",
  },

  sharpe_ratio: {
    baby: "Imagine two friends who both made money investing. One took wild risks to get there, screaming down every hill. The other cruised calmly. The Sharpe Ratio tells you who was the better driver, not who went fastest, but who got the best speed for how scary the ride was.",
    individual: "The Sharpe Ratio answers a simple question: are you being paid enough for the risk you're taking? It compares your return above the \"risk-free\" rate, like a government bond, to how much your portfolio swings around to get there. A higher Sharpe means more return per unit of risk — above 1.0 is generally considered good, above 2.0 is excellent, and below 0 means a savings account would have done better.",
    expert: "Developed by William Sharpe in 1966 (originally the \"reward-to-variability ratio\"), the Sharpe ratio is defined as (Portfolio Return − Risk-Free Rate) / Standard Deviation of Returns, and it remains the most widely cited risk-adjusted performance metric in both academic finance and institutional reporting. Its significance lies in reframing the investment question from \"how much did you make\" to \"how much did you make relative to the risk taken to make it\" — a reframing that underpins the Capital Market Line and the broader mean-variance framework Sharpe helped formalise, work that contributed to his 1990 Nobel Prize in Economics. Its well-known limitation, treating upside and downside volatility as equally undesirable, is why it's typically read alongside the Sortino ratio in institutional due diligence rather than in isolation.",
  },

  sortino_ratio: {
    baby: "The Sharpe Ratio counts every bump in the road, even the fun ones. But going up fast isn't scary, it's the drops that hurt. The Sortino Ratio only counts the scary drops. A high score means your portfolio gives you smooth climbs without gut-wrenching falls.",
    individual: "Standard risk measures penalize a portfolio equally whether it swings up or down, but investors don't actually mind upside swings. The Sortino Ratio only counts the downside, the returns that fell below what you needed. It's a more honest picture of risk for anyone who cares about losses more than volatility itself.",
    expert: "The Sortino Ratio refines the Sharpe framework by replacing total standard deviation with downside deviation, the dispersion of returns falling below a minimum acceptable return (MAR), often the risk-free rate. This distinction matters most for strategies with asymmetric or non-normal return distributions, where a manager generating large positive spikes would be unfairly penalized under Sharpe's symmetric treatment of volatility. Institutionally, Sortino is frequently the preferred lens for evaluating hedge fund and options-based strategies, where upside convexity is a feature, not noise to be minimized.",
  },

  treynor_ratio: {
    baby: "Sharpe Ratio asks 'how bumpy was the whole ride?' The Treynor Ratio asks a narrower question: 'how bumpy was the ride caused by the big highway you were driving on (the market), not your own swerving?' It's for when you've already got a smooth car and just want to know how well you used the highway.",
    individual: "The Treynor Ratio measures return earned per unit of market risk, or beta, rather than total volatility. It's most useful when comparing already-diversified portfolios, where leftover stock-specific risk has mostly been eliminated, so what's left to judge is how well the portfolio used its exposure to the broader market.",
    expert: "Developed by Jack Treynor in the early 1960s, work that predates and helped inspire the Capital Asset Pricing Model, the Treynor ratio is defined as (Portfolio Return − Risk-Free Rate) / Beta. Its defining feature is using systematic risk, beta, rather than total volatility as the risk denominator, which makes it most appropriate for evaluating a sub-portfolio or manager within a larger, already-diversified allocation, where unsystematic risk is assumed to be diversified away and irrelevant to compensate for. It's a staple of manager evaluation in institutional settings — pension consultants and fund-of-funds allocators use it to isolate whether a manager is being paid fairly for market exposure alone, distinct from stock-picking skill, which is closer to what alpha and the information ratio are designed to capture.",
  },

  information_ratio: {
    baby: "Imagine you're not just trying to beat 'doing nothing,' you're trying to beat a specific rival team, like the S&P 500. The Information Ratio measures how consistently you beat that rival, and how steady your lead is, not just how big it is on your best day.",
    individual: "The Information Ratio measures how much extra return your portfolio generates versus a benchmark, per unit of risk taken to deviate from that benchmark. A higher number means more consistent outperformance, not just occasional lucky wins. It's the metric active fund managers are judged on when their whole job is to beat an index, not just to make money.",
    expert: "The Information Ratio is defined as Active Return, portfolio return minus benchmark return, divided by Tracking Error, the standard deviation of that active return, and it serves as the Sharpe ratio's analogue for active management, where the \"risk-free rate\" is replaced by a specific benchmark and the object of scrutiny is skill in generating excess return rather than absolute return. It is the central metric in Grinold and Kahn's \"Fundamental Law of Active Management,\" which ties a manager's expected Information Ratio to their forecasting skill (the Information Coefficient) and breadth of independent bets, a framework still taught as core doctrine in quantitative asset management. In practice, an IR above 0.5 is considered good and above 1.0 exceptional and rare, which is why institutional manager searches treat consistently high IR as one of the strongest available signals of genuine, repeatable skill rather than benchmark-hugging luck.",
  },

  max_drawdown: {
    baby: "Imagine your money is a rollercoaster car. Max Drawdown is the biggest drop from the highest point of the ride to the lowest point right after, before it climbs back up. It's not about the final score, it's about the scariest part of the fall.",
    individual: "Max Drawdown is the largest drop your portfolio experienced from a peak to a low point, before recovering, over the period you're looking at. It's one of the most emotionally honest risk numbers there is, because it tells you the worst pain you would have actually felt holding the investment, not just an average or a theoretical worst case.",
    expert: "Maximum Drawdown is defined as the largest peak-to-trough decline in cumulative value over a specified window, expressed as a percentage, and unlike volatility, it's a path-dependent measure — it captures the sequence of losses, not just their statistical dispersion. It matters enormously in practice because drawdown, not volatility, is what triggers real-world consequences: margin calls, redemption requests, and the psychological capitulation that causes investors to sell at the worst possible time. Drawdown-based statistics — Max Drawdown, the Calmar ratio (return divided by max drawdown), and drawdown duration (time to recovery) — are core risk controls at CTAs and hedge funds precisely because a strategy's long-run average return means little if the drawdown along the way was severe enough to force investors, or the manager's own risk limits, out of the position before recovery.",
  },

  var_95: {
    baby: "Imagine 100 possible days. VaR 95% draws a line and says: 'On 95 of those days, you won't lose more than this much.' It's not a promise, it's a fence around the normal bad days, not the once-in-a-while disasters.",
    individual: "VaR at 95% confidence tells you the most you'd expect to lose in a single day, 95% of the time. On the remaining 5% of days, roughly one trading day a month, losses can be worse than this number. Think of it as your everyday bad-day budget, not a worst-case guarantee.",
    expert: "Value at Risk at the 95% confidence level identifies the loss threshold that will not be exceeded on 95% of trading days, based on the historical or parametric distribution of returns — equivalently, the 5th percentile of the return distribution. Popularised by J.P. Morgan's RiskMetrics framework in the mid-1990s, VaR became the de facto standard risk disclosure metric for banks and asset managers through the Basel I and II accords, largely because it compresses a complex return distribution into a single, board-reportable number. Its principal shortcoming, one that became infamous after the 2008 financial crisis, is that VaR says nothing about the magnitude of losses beyond the threshold — two portfolios can share an identical 95% VaR while one has a catastrophic tail and the other doesn't, which is exactly the blind spot Expected Shortfall (CVaR) was designed to close.",
  },

  cvar_95: {
    baby: "VaR tells you where the bad days start. CVaR asks: once we're already having a bad day, how bad does it usually get? It's the difference between 'the storm starts here' and 'here's how wet you'll actually get.'",
    individual: "VaR gives you a single cutoff, the loss you likely won't exceed. But it says nothing about what happens if you do exceed it. CVaR answers that question directly, it's the average loss on the worst days beyond that cutoff, which is often what actually breaks a portfolio.",
    expert: "Expected Shortfall, also known as Conditional Value at Risk, addresses VaR's central limitation: VaR marks a quantile boundary but provides no information about the severity of losses beyond it. CVaR is the average of all losses at or beyond the VaR threshold, effectively describing the shape of the tail rather than just its starting point. This property, combined with CVaR's coherence as a risk measure (unlike VaR, it satisfies subadditivity, meaning diversification can never make it worse), led regulators to make it the new standard: the Basel Committee's Fundamental Review of the Trading Book replaced 99% VaR with 97.5% Expected Shortfall as the required capital measure for market risk.",
  },

  var_99: {
    baby: "VaR 99% is the same fence as VaR 95%, just built further out. Instead of marking off the normal bad days, it marks off almost all days, only the rarest 1-in-100 disaster days are allowed past this line.",
    individual: "VaR at 99% confidence is a stricter version of the same idea as VaR 95%, the most you'd expect to lose on a typical bad day, but pushed out to only the worst 1% of days instead of the worst 5%. Because it targets rarer, more extreme days, the number is always larger than VaR 95%. It's the threshold institutions use when they want to understand truly severe, not just uncomfortable, downside scenarios.",
    expert: "VaR at the 99% confidence level identifies the 1st percentile loss threshold, a materially more conservative cutoff than the 95% level, capturing roughly one severe day in every 100 trading days, about two to three times a year. The gap between 95% and 99% VaR is itself informative: a wide gap signals fat tails, meaning the distribution has more extreme outliers than a normal distribution would predict, a hallmark of financial returns generally and a key reason regulators require reporting at multiple confidence levels rather than one. 99% VaR is the confidence level historically mandated under the Basel II market risk framework for regulatory capital calculations, precisely because capital buffers need to be sized against genuinely rare, severe events, not routine daily fluctuations.",
  },

  cvar_99: {
    baby: "If VaR 99% marks where the worst 1-in-100 days begin, CVaR 99% asks: once you're in one of those truly rare disaster days, how bad does it usually get, on average? It's the size of the worst storms, not just where the worst-storm zone starts.",
    individual: "CVaR at 99% is the average loss on your worst 1% of days, the rare, severe scenarios rather than the everyday bad days. It's the number that matters most for understanding tail risk, what happens in a true crisis, not just a rough week. If this number is dramatically larger than CVaR 95%, it's a sign your portfolio has \"fat tails,\" occasional extreme moves a simpler risk picture would miss.",
    expert: "CVaR at 99% is the expected value of losses conditional on breaching the 99% VaR threshold, the average severity of the roughly 1-in-100 worst outcomes, and it's the tail statistic most directly relevant to catastrophic, capital-impairing scenarios rather than routine drawdowns. Because it's estimated from the extreme, sparsely populated tail of the empirical return distribution, it's also the most statistically noisy of the standard risk metrics, sensitive to sample size and to whether the historical window captured a genuine tail event (a 2008 or 2020) or not, a limitation that has pushed practitioners toward supplementing it with Extreme Value Theory and stress testing rather than relying on historical CVaR alone. It's the metric most aligned with the post-2008 regulatory shift toward tail-risk-aware capital requirements, reflecting the industry's recognition that historical VaR models badly underestimated the depth of true crisis losses.",
  },

  beta: {
    baby: "Imagine the whole stock market is one big ocean wave. Beta tells you how much your little boat bobs up and down compared to that wave. A beta of 2 means when the ocean rises 1 foot, your boat rises 2. A beta of 0.5 means you barely notice the wave at all.",
    individual: "Beta measures how much your portfolio tends to move relative to the overall market. A beta of 1.5 means your portfolio tends to swing about 50% more than the market, in either direction, up or down. A beta below 1 means you're more defensive, typically falling less when the market falls, but also gaining less when it rises.",
    expert: "Beta is the slope coefficient from regressing a portfolio's excess returns against the market's excess returns, and it's the central risk measure of the Capital Asset Pricing Model (CAPM), formalised independently by Sharpe, Lintner, and Mossin in the 1960s. CAPM's core insight is that only systematic risk, the portion of volatility correlated with the broad market and therefore un-diversifiable, should be compensated with expected return; idiosyncratic, stock-specific risk can be eliminated through diversification and the market pays nothing extra for bearing it. Beta remains the standard input for estimating a stock's cost of equity in discounted cash flow valuation, and it's the benchmark against which alpha, the return left over after accounting for market exposure, is measured — the two metrics are conceptually inseparable in performance attribution.",
  },

  alpha: {
    baby: "Imagine your friend says 'I ran faster than everyone else on the track.' But what if they were running downhill while everyone else ran uphill? Alpha strips out the 'easy downhill' part, the market helping everyone, and tells you how much of your win was really you.",
    individual: "Alpha is the extra return you earned beyond what your risk level alone would predict. If the market's move and your portfolio's beta suggested you should have returned 18%, but you actually returned 25%, your alpha is +7%, real outperformance, not just riding a rising market. Positive alpha means your specific decisions, not just market exposure, added value.",
    expert: "Alpha is the intercept term in the CAPM regression, the return unexplained by beta-adjusted market exposure, and it represents the portion of performance attributable to skill (stock selection, timing, or factor exposure not captured by the model) rather than to bearing systematic market risk. Michael Jensen's 1968 study, which found that the average mutual fund manager generated negative alpha net of fees, remains one of the foundational papers behind the passive investing movement and the broader efficient market hypothesis debate. In modern practice, \"alpha\" has expanded beyond its single-factor CAPM origins into multi-factor frameworks (Fama-French, Carhart) that isolate skill after controlling for size, value, and momentum exposures as well as market beta, since a manager who simply overweights small-cap or momentum stocks can appear to generate alpha under CAPM that's really just an uncompensated factor tilt.",
  },

  diversification_score: {
    baby: "Imagine you pack for a trip and bring five umbrellas. If it doesn't rain, you're carrying dead weight for nothing. Diversification is about packing different useful things, a raincoat, sunscreen, snacks, so that whatever the weather does, you're covered. The Diversification Score tells you how much you're really 'five umbrellas' versus a well-packed bag.",
    individual: "The Diversification Score measures how spread out your risk really is, based on how closely your holdings move together, not just how many different stocks you own. Owning five tech stocks feels diversified, but if they all rise and fall together, you haven't actually reduced your risk much. A high score means your holdings tend to zig and zag independently, cushioning the portfolio when any one of them has a bad day.",
    expert: "This score is derived from the average pairwise correlation across a portfolio's holdings, converted to a 0-100 scale where lower average correlation produces a higher diversification score. It operationalises the core insight of Modern Portfolio Theory: portfolio variance is not simply the weighted average of individual asset variances, it also depends on the covariances between assets, meaning that combining imperfectly correlated assets reduces total risk without necessarily reducing expected return. This is precisely why the metric is window-dependent rather than a fixed property of the underlying stocks: correlations are regime-sensitive, tending to rise sharply during systemic stress, a phenomenon well-documented in the empirical finance literature as \"correlation breakdown\" or \"correlations go to one in a crisis,\" meaning a portfolio that looks well-diversified in calm markets can lose much of that protection exactly when it's needed most.",
  },

  correlation_matrix: {
    baby: "Imagine everyone in your portfolio is a dancer. The Correlation Matrix shows you who dances in sync with who. If two dancers always step left and right at the exact same time, they're basically doing the same dance, so having both doesn't add anything new to the show.",
    individual: "The Correlation Matrix shows how every pair of holdings in your portfolio moves relative to each other, on a scale from -1 to +1. Values near +1 mean two stocks tend to rise and fall together, so holding both gives you little extra protection. Values near 0 mean they move independently, and values near -1 mean they tend to move in opposite directions, the strongest kind of natural hedge.",
    expert: "The correlation matrix presents the Pearson correlation coefficients between every pair of asset return series in the portfolio, forming the covariance structure that, together with individual asset volatilities, entirely determines portfolio-level variance under Markowitz's mean-variance framework. It's the direct numerical input behind concepts like the efficient frontier and diversification scoring, and reading it well requires more than eyeballing which pairs are \"high\" or \"low\" — practitioners specifically watch for correlation clustering, groups of assets that move as a bloc and effectively reduce the portfolio's true number of independent bets, and for correlation instability across market regimes, since correlations estimated over a calm historical window are notoriously unreliable predictors of correlations during a crisis, when diversification benefits are needed most and tend to evaporate.",
  },

  rolling_metrics: {
    baby: "A single Volatility number is like a school report card for the whole year. Rolling Volatility is like checking your grades every single week instead, so you can actually see whether you're improving, slipping, or steady, not just one final number that hides the whole story.",
    individual: "Rather than showing one volatility or Sharpe number for the entire period, rolling metrics recalculate them continuously using a moving window, like the trailing 30 days, so you can see how risk and risk-adjusted performance have changed over time. A rising rolling volatility line means risk has been increasing recently, even if the full-period average still looks calm. It's a way to catch a shift in your portfolio's behaviour early, instead of only seeing it after the fact in the year-end average.",
    expert: "Rolling metrics apply a moving-window calculation, commonly 21, 30, or 60 trading days, to a return series, recomputing volatility or the Sharpe ratio at each point in time rather than producing a single static, full-sample statistic. This transforms a point estimate into a time series, exposing regime shifts, volatility clustering, and drift in risk-adjusted performance that a single backward-looking average would completely obscure — a full-period Sharpe of 1.2 could be hiding a portfolio that was excellent for nine months and dangerous for three. This technique is foundational to volatility modelling more broadly (it's the intuitive precursor to GARCH-family models, which formalise volatility clustering statistically), and it's standard practice in institutional risk monitoring dashboards, where a deteriorating rolling Sharpe trend is often treated as an earlier and more actionable warning signal than a single trailing full-period number.",
  },

  monte_carlo: {
    baby: "Imagine you could rewind time and replay next year 1,000 different times, letting the dice roll a little differently each time. Monte Carlo Simulation does exactly that with your portfolio, running it forward 1,000 times to show you the full range of what could realistically happen, not just one guess.",
    individual: "Monte Carlo Simulation runs your portfolio forward thousands of times using randomised scenarios built from its historical return and volatility patterns, showing you a full range of possible future outcomes rather than a single prediction. It's not a forecast of what will happen, it's an honest picture of what could plausibly happen, including the best cases, the worst cases, and everything typical in between. A statement like \"75% chance of profit\" comes directly from counting how many of those simulated futures ended up ahead.",
    expert: "Monte Carlo simulation generates thousands of synthetic future return paths by repeatedly sampling from a model of the portfolio's return-generating process, commonly a multivariate distribution calibrated to historical mean, volatility, and cross-asset correlation, often via Cholesky decomposition, to correctly preserve how assets move together rather than treating each independently. Originally developed at Los Alamos in the 1940s for nuclear chain-reaction modelling, the method was adapted to finance in the 1960s and 1970s and is now standard for pricing path-dependent derivatives, stress-testing pension liabilities, and, as used here, projecting a range of portfolio outcomes rather than a single point estimate. Its central assumption, and the thing most worth scrutinising, is that the future will statistically resemble the historical calibration window: it can't invent a genuinely unprecedented shock, which is exactly the gap that scenario analysis and stress testing are designed to fill.",
  },

  scenario_analysis: {
    baby: "Imagine three different weather forecasts for your camping trip: a storm, a normal cloudy day, and perfect sunshine. Bear, Base, and Bull scenarios are the same idea for your money, three honest guesses at how things could go: rough, normal, or great, so you're never caught totally off guard.",
    individual: "Bear, Base, and Bull scenarios show how your portfolio might perform under three distinct conditions: a downturn (bear), a typical or expected environment (base), and a strong rally (bull). Instead of relying on one central forecast, this gives you a realistic range bracketed by a rough outcome and a great one, helping you understand what you're actually exposed to on both ends, not just the average case.",
    expert: "Scenario analysis using bear, base, and bull cases is a form of conditional forecasting that deliberately anchors projections to explicit macro or market narratives, rather than to a single statistical distribution, complementing probabilistic tools like Monte Carlo simulation with structured, interpretable branches. This approach is standard practice in both equity research, where analysts publish bear/base/bull price targets tied to specific assumptions about growth, margins, or multiples, and institutional asset allocation, where committees stress portfolios against named macro regimes like a recession, a soft landing, or above-trend growth, because scenario framing forces explicit articulation of the assumptions driving each outcome, making the forecast auditable and debatable in a way a single blended expected return is not. Its main limitation is scenario selection bias: the framework is only as good as the scenarios chosen, and it can create false confidence if the bear case isn't genuinely severe enough to capture real tail risk.",
  },

  efficient_frontier: {
    baby: "Imagine trying every possible mix of ingredients for a smoothie, thousands of combinations, and plotting how tasty versus how healthy each one is. The Efficient Frontier is the line connecting the best combinations, the ones where you can't get more tasty without giving up healthy, or vice versa. Anything below that line is just a worse recipe.",
    individual: "The Efficient Frontier plots thousands of possible portfolios, built from different combinations of your chosen stocks, showing return on one axis and risk on the other. The curved edge along the top represents the best possible portfolios: for each level of risk, the combination that gives you the highest possible return. If your actual portfolio sits below that curve, the same risk you're taking could have earned you more, just by rebalancing your weights.",
    expert: "The efficient frontier is the central geometric construct of Harry Markowitz's 1952 Modern Portfolio Theory, work that earned him the 1990 Nobel Prize in Economics alongside Sharpe: among all possible portfolios constructable from a given asset universe, it traces the set that is mean-variance efficient, meaning no other combination of the same assets offers a higher expected return for the same level of volatility, or lower volatility for the same expected return. It's generated by solving a constrained quadratic optimisation problem across the full covariance matrix of asset returns, and portfolios lying strictly below the frontier are, by construction, mathematically dominated. Its well-known practical fragility is that it's highly sensitive to estimation error in expected returns, a criticism formalised by Michaud in the 1980s as \"estimation-error maximisation,\" which is why institutional practitioners typically pair frontier analysis with resampling, shrinkage estimators, or Black-Litterman-style Bayesian blending rather than optimising on raw historical inputs alone.",
  },

  stress_testing: {
    baby: "Imagine testing a new umbrella not by guessing if it'll rain, but by actually standing it in the exact storm from last October, and the exact storm from three years ago. Historical Stress Testing takes your portfolio today and drops it into real past disasters, like 2008 or the COVID crash, to see how it would have actually held up.",
    individual: "Historical Stress Testing takes your current portfolio and applies it to real, specific crisis periods from the past, like the 2008 financial crisis or the 2020 COVID crash, to show how it would have performed if that exact event happened again today. Unlike a general risk number, this shows something concrete and visceral: a specific, real scenario and a specific, real loss. It's the difference between knowing you could lose money in a crash, and seeing exactly what that would have looked like.",
    expert: "Historical stress testing applies a portfolio's current holdings and weights to the actual observed returns from a defined historical crisis window, rather than a modelled or hypothetical shock, answering the question: what would this exact portfolio have done during a real, specific event? It's a required component of bank stress testing regimes, including the Federal Reserve's CCAR/DFAST programs, and is standard practice in institutional risk committees precisely because it grounds tail-risk assessment in events that actually happened, sidestepping debates about whether a hypothetical shock is realistic. Its central limitation is that it's inherently backward-looking: it can only test against crises that have already occurred, meaning today's specific vulnerabilities, a concentration or exposure that didn't exist in 2008, may go completely untested unless paired with forward-looking hypothetical or reverse stress tests designed to specifically target a portfolio's current composition.",
  },

  backtesting: {
    baby: "Imagine you invented a new way to pick teams for a game, and before betting your allowance on it, you replay every game from last season using your new method to see how it would have done. Backtesting is that, but for your investment strategy: rewinding history and checking, 'if I'd actually done this, would it have worked?'",
    individual: "Backtesting takes your current portfolio strategy and replays it against real historical market data to see how it would have actually performed, year by year, compared to simpler alternatives like an equal-weighted split or the S&P 500. It's a reality check: does your specific mix of stocks and weights genuinely add value, or would a simpler approach have done just as well, or better? It's one of the most direct ways to validate a strategy before committing real money to it going forward.",
    expert: "Backtesting evaluates a strategy or portfolio construction rule by applying it retroactively to historical data and measuring the performance that would have resulted, typically benchmarked against naive alternatives, equal-weight, market-cap-weighted, or a passive index, to isolate whether the strategy's specific construction actually added value. It's foundational to quantitative strategy development, but it carries well-documented statistical hazards: look-ahead bias (accidentally using information that wouldn't have been available at the time), survivorship bias (testing only on assets that happened to survive to the present), and overfitting, where a strategy is tuned so precisely to historical data that it captures noise rather than a genuine, repeatable edge, a risk serious enough that quant researchers, notably Bailey, Borwein, López de Prado, and Zissis in their work on backtest overfitting, have proposed formal statistical corrections like the Deflated Sharpe Ratio specifically to account for it. A backtest is necessary evidence for a strategy but is never sufficient proof it will work going forward, since it's fundamentally a statement about the past, not a guarantee about a regime that hasn't happened yet.",
  },

  sector_exposure: {
    baby: "Imagine your team is made up entirely of goalkeepers. Great at one thing, but what happens when you need someone to score? Sector Exposure shows you what 'positions' your portfolio is actually playing, like Tech, Healthcare, or Energy, so you can see if you've accidentally built an all-goalkeeper team.",
    individual: "Sector Exposure shows how your portfolio's money is spread across different parts of the economy, like Technology, Healthcare, or Energy, weighted by how much you actually hold in each. It matters because stocks in the same sector often move together for the same underlying reasons, so heavy concentration in one sector means your portfolio's fate is more tied to that sector's fortunes than you might realise, even if you technically own several different stocks.",
    expert: "Sector exposure aggregates portfolio weight by GICS, the Global Industry Classification Standard jointly maintained by MSCI and S&P and used as the common classification standard across most institutional equity research and index construction. It matters because sector membership is one of the strongest empirical drivers of return correlation and shared macro sensitivity, stocks within a sector tend to respond similarly to the same interest-rate, commodity-price, or regulatory shocks, meaning a portfolio that appears diversified by holding count can still carry concentrated, correlated risk if those holdings cluster in one or two sectors. Sector-relative positioning, overweight or underweight versus a benchmark like the S&P 500's sector composition, is also one of the standard components of institutional performance attribution frameworks such as the Brinson model, which decompose a portfolio's excess return into allocation effects (sector bets) and selection effects (stock-picking within sectors), making sector exposure a foundational input for understanding not just risk but also the source of past performance.",
  },
}
