// Content for /methodology — a technical deep-dive for a quant/finance-
// literate audience, sourced directly from stats_engine.py, data_fetcher.py,
// and api.py (not from memory of textbook conventions). Every `standard`
// field states the CFA-curriculum/standard-literature formula; every
// `implementation` field is pulled literally from the code, including exact
// constants, with any divergence from the standard formula stated plainly.
// Where the code doesn't explain *why* a choice was made, this file doesn't
// invent a reason — see the "gaps" section at the bottom of the page itself,
// and the report given alongside this file's creation.

export const APP_URL = import.meta.env?.VITE_APP_URL ?? '/app'

export const constants = [
  { label: 'Trading days / year', value: '252', note: 'Used to annualise every daily-return-based figure in the app.' },
  { label: 'Risk-free rate', value: '4.5%', note: 'A static constant (stats_engine.py: RISK_FREE_RATE = 0.045). Not fetched from a live Treasury yield — see Sharpe/Sortino/Treynor below.' },
  { label: 'Rolling window', value: '30d default', note: 'User-adjustable to 20d / 60d / 90d via the Risk Analysis tab. Passed through as rolling_window on every /api/analyse call.' },
  { label: 'Monte Carlo paths', value: '1,000', note: 'Over a 252-trading-day (1yr) horizon. Re-run three times per analysis — bear / base / bull drift scenarios.' },
  { label: 'Efficient frontier samples', value: '5,000', note: 'Randomly weighted portfolios simulated per analysis — see the Efficient Frontier section for why this isn’t a QP solve.' },
  { label: 'VaR / CVaR confidence', value: '95% & 99%', note: 'Both computed on every run, unconditionally — not caller-configurable. An earlier version of AnalyseRequest declared an unused confidence field; removed once this page’s own audit surfaced that nothing read it.' },
]

export const divergencesCallout = [
  {
    title: 'Returns are annualised geometrically (CAGR), everywhere that matters',
    body: 'compute_annualised_return raises the cumulative return to the power (252 / n_days) rather than multiplying a mean daily return by 252. compute_efficient_frontier uses the mathematically identical formula (via a log-sum-exp reduction, for speed across 5,000 simulated portfolios at once) specifically so the frontier and the single "Your Portfolio" dot are computed the same way — an inconsistent annualisation method between the two would make the dot appear inside or outside the simulated cloud for reasons that have nothing to do with the portfolio’s actual risk/return.',
  },
  {
    title: 'Monte Carlo draws from the real covariance structure, not an independent normal per asset',
    body: 'compute_monte_carlo Cholesky-decomposes the daily covariance matrix of the requested tickers and multiplies standard-normal draws through the resulting lower-triangular matrix, so simulated daily returns for each asset carry the same correlation the historical data actually showed. If the covariance matrix isn’t positive-definite — numpy.linalg.cholesky raises LinAlgError — the code falls back to drawing the portfolio’s own daily returns from a single univariate normal distribution instead, discarding the correlation structure for that run. The code doesn’t log or surface when this fallback fires; the response includes a "method" field ("cholesky" or "fallback_univariate") but the frontend doesn’t currently display it.',
  },
  {
    title: 'VaR and CVaR are computed at both 95% and 99% confidence, unconditionally',
    body: 'compute_all_metrics calls compute_cvar twice — once at confidence=0.95, once at confidence=0.99 — and both go into every /api/analyse response as var_cvar and var_cvar_99, regardless of what a caller passes for anything else. (An earlier version of AnalyseRequest’s pydantic schema declared a confidence field that nothing in the handler ever read — this page’s own audit surfaced that dead field, and it’s since been removed rather than left to silently do nothing.)',
  },
  {
    title: 'The diversification score is a direct function of whichever period you’re looking at',
    body: 'compute_diversification_score takes the correlation matrix as its only input — it doesn’t compute or cache anything itself over a fixed lookback. That correlation matrix is built from compute_returns(prices) over exactly the start_date/end_date window the analysis was run over. Change the period, and the score changes, because the correlation structure the assets actually exhibited changes — this isn’t a separate design decision layered on top, it’s the direct, unavoidable consequence of computing correlation from whatever data window you feed it.',
  },
]

export const dataSourcing = {
  heading: 'Where the numbers come from',
  paragraphs: [
    'Every metric on this page is computed from prices returned by data_fetcher.py’s fetch_closing_prices, which calls yfinance’s yf.download() with `auto_adjust=True`. That means every price series feeding every return, volatility, and correlation figure on this page is split- and dividend-adjusted — not the raw traded close. This matters most for cumulative-return comparisons against a second, unadjusted data source: an adjusted close will differ from an unadjusted one by roughly the dividend yield paid between the two dates being compared, converging to zero difference as you approach the most recent trading day.',
    'Price data is cached in Redis for 24 hours per unique (tickers, start_date, end_date) request (cache.py, wrapping fetch_closing_prices and fetch_with_benchmark) — fails open, so the app runs identically, just uncached, if Redis is unreachable. A ticker that resolves to fewer than 5 rows of data is deliberately never cached (data_fetcher.py: MIN_ROWS_TO_CACHE), so a transient fetch failure gets retried on the next request rather than being served back as a cached failure for a full day.',
    'A ticker that yfinance can’t resolve at all — an invalid symbol, not a rate-limited one — is distinguished explicitly in code from an actual Yahoo Finance rate-limit response (yfinance_utils.py: TickerNotFoundError vs. YFinanceRateLimitError), so a bad ticker symbol and a genuine rate limit surface as different, accurate error messages rather than both reading as "Yahoo is rate-limiting this server."',
    'Real-time quotes and company fundamentals (Valuation tab, stock detail drawer) come from a separate source — Finnhub, not yfinance — cached for 1 hour. Historical price series for every metric on this page come from yfinance. The two are never mixed within a single metric.',
  ],
}

export const metrics = [
  {
    id: 'annualised-return',
    index: '01',
    label: 'Return',
    heading: 'Annualised return',
    standard: 'CAGR = (V_end / V_start)^(periods_per_year / n_periods) − 1',
    standardNote: 'The geometric, compounding-aware way to express a multi-period return as a single annual rate — standard CFA-curriculum treatment, and the version that answers "what constant annual rate would have produced this same outcome," which a simple arithmetic mean of daily returns does not.',
    implementation: 'cumulative = (1 + portfolio_returns).prod()\nreturn cumulative ** (252 / n_days) - 1',
    implementationNote: 'Exactly the standard CAGR formula, with `periods_per_year` hardcoded to `TRADING_DAYS = 252` and `n_periods` the actual number of trading days returned for the requested window. No divergence here — this is the one figure the rest of the codebase is deliberately kept consistent with (see the CAGR callout above). `compute_efficient_frontier` re-derives the identical quantity via `exp(sum(log1p(returns)) * 252/n_obs) - 1`, which is algebraically the same formula computed via log-sums so it vectorises across 5,000 simulated portfolios at once.',
    whereItAppears: '`Dashboard` (**Annual Return** metric card), `Backtest` (per-strategy annualised return for Your Portfolio / Equal Weight / S&P 500), and as the return axis on `Efficient Frontier`.',
  },
  {
    id: 'annualised-volatility',
    index: '02',
    label: 'Volatility',
    heading: 'Annualised volatility',
    standard: 'σ_annual = σ_daily × √(periods_per_year)     or, for a portfolio:     σ_p = √(wᵀ Σ w)',
    standardNote: 'The square-root-of-time scaling rule (assumes i.i.d. daily returns), or the direct portfolio-variance formula using the covariance matrix Σ and weight vector w — both standard, and mathematically equivalent when Σ is built from the same return series.',
    implementation: 'cov_matrix = returns.cov() * 252\nvolatility = sqrt(weights.T @ cov_matrix.values @ weights)',
    implementationNote: 'The top-level `annualised_volatility` figure in every API response uses the covariance-matrix formula (σ_p = √(wᵀΣw)), with the daily covariance matrix annualised by multiplying by 252 before the matrix multiply. Worth being precise about: the Sharpe and Sortino ratios elsewhere in the same response do **not** reuse this figure — they call a separate function, `compute_volatility`, which is simply `portfolio_returns.std() * sqrt(252)`, the direct sample standard deviation of the realised, already-weighted portfolio return series. Both are the textbook-correct way to compute portfolio volatility and should be numerically near-identical; they’re just two different code paths arriving at the same quantity, not a single shared calculation.',
    whereItAppears: '`Dashboard` (**Volatility** metric card, via the covariance-matrix path) and `Risk Analysis` (**Rolling Volatility** chart, a windowed version of the direct-std path — see Rolling metrics below).',
  },
  {
    id: 'sharpe-ratio',
    index: '03',
    label: 'Sharpe',
    heading: 'Sharpe ratio',
    standard: 'Sharpe = (R_p − R_f) / σ_p',
    standardNote: 'Excess return per unit of total volatility — William Sharpe’s original 1966 formulation, effectively universal across risk literature and the CFA curriculum.',
    implementation: 'ann_return = compute_annualised_return(portfolio_returns)   # CAGR\nann_vol    = portfolio_returns.std() * sqrt(252)\nreturn (ann_return - 0.045) / ann_vol',
    implementationNote: 'CAGR return, minus the static 4.5% risk-free constant, over the annualised sample standard deviation of realised daily portfolio returns. Returns `0.0` if volatility is exactly zero rather than dividing by zero. Two things worth flagging precisely, not glossed over: first, the risk-free rate’s source — `RISK_FREE_RATE = 0.045` is a hardcoded module constant, not fetched from any live Treasury yield, with no code comment on why 4.5% specifically. Second, using CAGR for the numerator here is itself a deliberate departure from the most commonly cited textbook annualisation of a periodic-return Sharpe ratio, which uses the **arithmetic** mean of periodic excess returns scaled by √T, not a compounded return — see the Information Ratio section below, where this distinction is checked against the literature and explained in full; that ratio uses the arithmetic form, which is actually the more conventional one of the two.',
    whereItAppears: '`Dashboard` (**Sharpe Ratio** metric card) and `Backtest` (per-strategy Sharpe for Your Portfolio / Equal Weight / S&P 500).',
  },
  {
    id: 'sortino-ratio',
    index: '04',
    label: 'Sortino',
    heading: 'Sortino ratio',
    standard: 'Sortino = (R_p − MAR) / DD,     DD = √( (1/N) Σ min(r_i − MAR, 0)² )',
    standardNote: 'Like Sharpe, but the denominator — downside deviation (DD) — is a semi-deviation computed over **all** N observations, squaring only the shortfalls below a minimum acceptable return (MAR, often 0 or the risk-free rate) and treating every period above MAR as a zero contribution. This is the standard, CFA-recognised definition.',
    implementation: 'negative_returns = portfolio_returns[portfolio_returns < 0]\ndownside_std = negative_returns.std() * sqrt(252)\nreturn (ann_return - 0.045) / downside_std',
    implementationNote: 'This is a real divergence from the textbook downside-deviation formula, worth stating precisely rather than glossing over. Varense filters the return series down to only the days with a strictly negative return, then takes the **plain sample standard deviation of that subset** — pandas’ `.std()`, which divides by (N_negative − 1) and measures each negative return’s distance from the **mean of the negative returns**, not from a fixed MAR of 0. The standard formula instead divides by the **full** sample size N (all trading days, not just the down days) and measures each down-day’s distance from MAR directly, with up days contributing exactly zero rather than being excluded from the count. The two will diverge most when a portfolio has many small negative days clustered near zero (Varense’s version can read higher, since N_negative ≪ N shrinks the effective sample its variance is computed over) — the code doesn’t comment on this choice, so no further rationale is claimed beyond what’s implemented. MAR is implicitly 0 (the `< 0` filter), not the risk-free rate. Separately, the numerator uses CAGR rather than the arithmetic mean more commonly cited for this style of ratio — see the Information Ratio section below for that distinction checked against the literature.',
    whereItAppears: '`Dashboard` (**Sortino Ratio** metric card).',
  },
  {
    id: 'treynor-ratio',
    index: '05',
    label: 'Treynor',
    heading: 'Treynor ratio',
    standard: 'Treynor = (R_p − R_f) / β_p',
    standardNote: 'Excess return per unit of systematic (market) risk, using beta rather than total volatility in the denominator — standard CFA-curriculum definition, intended for a portfolio that’s one holding within a diversified whole.',
    implementation: 'beta = compute_beta_alpha(portfolio_returns, benchmark_returns)["beta"]\nreturn (annualised_return - 0.045) / beta',
    implementationNote: 'CAGR return minus the same static 4.5% risk-free constant, divided by beta (see Beta & Alpha below for exactly how beta itself is estimated). Returns `0.0` if beta is exactly zero. Same CAGR-vs-arithmetic-mean numerator point applies here as for Sharpe above — see the Information Ratio section below.',
    whereItAppears: '`Risk Analysis` tab, only when a benchmark is included in the analysis (Treynor requires beta, which requires the S&P 500 series).',
  },
  {
    id: 'information-ratio',
    index: '06',
    label: 'Info ratio',
    heading: 'Information ratio',
    standard: 'IR = E[R_p − R_b] / σ(R_p − R_b),     annualised as (mean daily active return × T) / (daily tracking error × √T) = (mean/std) × √T',
    standardNote: 'Active return per unit of tracking error against a benchmark — Grinold & Kahn’s canonical definition (Active Portfolio Management, 2nd ed., p.114), and the formula most texts still cite today. It’s worth being exact about what "canonical" means here: the numerator is the **arithmetic** mean of periodic active returns, not a geometric/compounded one. That’s not an approximation of some purer version — it’s the definition. (It’s also a documented limitation of the formula in its own right: annualising an arithmetic difference between two return series isn’t the same as taking the arithmetic difference of the two series’ own annualised figures — a quirk inherited from the definition itself, not introduced by any particular implementation.)',
    implementation: 'active_returns = portfolio_returns - benchmark_returns  # daily, aligned\nreturn (active_returns.mean() / active_returns.std()) * sqrt(252)',
    implementationNote: 'Matches the Grinold-Kahn formula exactly. This was flagged during an earlier audit of this codebase as a possible inconsistency — Sharpe, Sortino, and Treynor all annualise their numerator geometrically via `compute_annualised_return` (CAGR), while this ratio’s numerator is implicitly arithmetic (mean_daily × 252, algebraically folded into the √252 term). Checked against the literature rather than assumed: the arithmetic form isn’t a simplification Varense introduced — it’s specifically what Grinold & Kahn define, and it’s **also** the form most commonly given for the Sharpe ratio itself when annualising from a return series (Sharpe’s own treatment: Sₜ = (μ/σ)√T, using the arithmetic mean μ). Seen against that, this ratio is arguably the most textbook-standard of the four in the codebase — it’s Varense’s own Sharpe, Sortino, and Treynor that substitute CAGR for the arithmetic mean, most likely to keep every ratio’s numerator consistent with the CAGR-based Annual Return figure shown elsewhere on the Dashboard, though the code itself doesn’t say so, so that’s offered as the likely explanation, not a documented fact. Conclusion: making this ratio CAGR-consistent with the other three would move it away from its own canonical definition, not toward a more correct one — left unchanged.',
    whereItAppears: '`Risk Analysis` tab, alongside Treynor — also only computed when a benchmark is included.',
  },
  {
    id: 'value-at-risk',
    index: '07',
    label: 'VaR',
    heading: 'Value at Risk',
    standard: 'VaRₕ = the loss such that P(loss > VaRₕ) = 1 − c, for confidence level c',
    standardNote: 'Three standard estimation methods exist: parametric (variance-covariance, assumes a return distribution), historical simulation (empirical, distribution-free), and Monte Carlo simulation. All three are "correct" VaR by definition — they differ in the assumption made to estimate the tail.',
    implementation: 'percentile = (1 - confidence) * 100\nvar_threshold = np.percentile(portfolio_returns, percentile)',
    implementationNote: 'Varense implements **historical simulation VaR** specifically — the empirical percentile of the realised daily portfolio return series, with no distributional assumption. It is not parametric (no normal-distribution assumption on returns) and not Monte-Carlo-based (it doesn’t use the simulated paths from the Monte Carlo tab at all). This is computed at both 95% and 99% confidence unconditionally, every run — `compute_all_metrics` calls `compute_cvar` (which returns VaR alongside CVaR) twice, once at each level, and both appear in every `/api/analyse` response as `var_cvar` and `var_cvar_99`, not caller-configurable.',
    whereItAppears: '`Dashboard` (**VaR 95%** metric card) and `Risk Analysis` (**Downside Risk** panel, both 95% and 99%).',
  },
  {
    id: 'cvar-expected-shortfall',
    index: '08',
    label: 'CVaR',
    heading: 'Conditional VaR / Expected Shortfall',
    standard: 'CVaRₕ = E[loss | loss > VaRₕ]',
    standardNote: 'The expected loss conditional on already being in the tail beyond VaR — always at least as severe as VaR by construction. The Basel Committee’s Fundamental Review of the Trading Book replaced 99% VaR with 97.5% Expected Shortfall as the required regulatory market-risk capital measure specifically because VaR says nothing about severity beyond its own threshold.',
    implementation: 'tail_returns = portfolio_returns[portfolio_returns <= var_threshold]\ncvar = tail_returns.mean()',
    implementationNote: 'The mean of every realised daily return at or below the VaR threshold — the direct, standard historical-simulation CVaR estimator, sharing the same tail-selection logic and the same 95%/99% dual-confidence computation as VaR above (same function, `compute_cvar`, returns both). No divergence from the standard formula. `n_tail_days` (the count of days the average is taken over) is included in the response but not currently surfaced in the UI.',
    whereItAppears: '`Dashboard` (**CVaR 95%** metric card) and `Risk Analysis` (**Downside Risk** panel, both 95% and 99%, shown alongside VaR).',
  },
  {
    id: 'max-drawdown',
    index: '09',
    label: 'Drawdown',
    heading: 'Maximum drawdown',
    standard: 'Drawdown_t = (V_t − Peak_t) / Peak_t,     Peak_t = max(V_0, …, V_t)     MaxDD = min(Drawdown_t)',
    standardNote: 'The largest peak-to-trough decline in cumulative wealth over the period — standard definition, no variation in how this is conventionally computed.',
    implementation: 'wealth_index = (1 + portfolio_returns).cumprod()\nrolling_peak = wealth_index.cummax()\ndrawdown_series = (wealth_index - rolling_peak) / rolling_peak\nmax_drawdown = drawdown_series.min()',
    implementationNote: 'Directly matches the standard formula — a running peak via `cummax()`, drawdown at every point relative to that peak, and the single worst value as the headline number. No divergence.',
    whereItAppears: '`Dashboard` (**Max Drawdown** metric card and the **Drawdown** chart) and `Backtest` (per-strategy max drawdown).',
  },
  {
    id: 'beta-alpha',
    index: '10',
    label: 'Beta & Alpha',
    heading: 'Beta and alpha',
    standard: 'β = Cov(R_p, R_b) / Var(R_b),     α = R_p − [R_f + β(R_b − R_f)]     (Jensen’s alpha, via CAPM)',
    standardNote: 'Beta as the regression slope of portfolio returns on benchmark returns; alpha as the realised return in excess of what CAPM says beta alone should have produced. Standard treatment throughout.',
    implementation: 'beta, daily_alpha = np.polyfit(bench_r, port_r, deg=1)\nalpha = daily_alpha * 252\ncapm_expected = 0.045 + beta * (bench_ann_return - 0.045)',
    implementationNote: 'Beta and the daily intercept come from a single ordinary-least-squares regression (`np.polyfit`, degree 1) of daily portfolio returns on daily benchmark returns — the slope is beta, standard practice. The daily intercept is annualised by straightforward multiplication by 252 (arithmetic scaling, not CAGR compounding) to get alpha — this is itself the conventional way Jensen’s alpha is annualised in practice, so it’s stated here for precision rather than flagged as a departure. `capm_expected` uses the standard CAPM formula with the benchmark’s own CAGR-based annualised return (`compute_annualised_return`, consistent with the rest of the codebase) as R_b.',
    whereItAppears: '`Dashboard` (**Beta** and **Alpha** metric cards, second row — only shown when a benchmark is included).',
  },
  {
    id: 'diversification-score',
    index: '11',
    label: 'Diversification',
    heading: 'Diversification score',
    standard: 'No single industry-standard formula exists for a single "diversification score" — this is Varense’s own construction, not a named textbook metric, built from a standard input (pairwise correlation).',
    standardNote: 'Common building blocks in the literature include average pairwise correlation, the Herfindahl-Hirschman Index on position weights, and effective-N measures — Varense uses the first of these.',
    implementation: 'off_diag = corr_matrix.values[upper_triangle_mask]\navg_corr = off_diag.mean()\nscore = round(clamp((1 - avg_corr) * 100, 0, 100))',
    implementationNote: 'The average of every pairwise correlation in the upper triangle of the correlation matrix (excluding the diagonal, which is always 1), mapped linearly onto a 0–100 scale: `avg_corr = 1.0` (everything moves in lockstep) scores 0; `avg_corr = 0.0` (uncorrelated) scores 100; a negative average correlation clamps at 100 rather than exceeding it. A single-asset portfolio has no pairs to average, and is scored 100 by explicit special-case (labelled "Single asset"). Labels: ≥70 "Well diversified," 40–69 "Moderate," <40 "Concentrated" — these thresholds are hardcoded with no documented justification in the code beyond the values themselves. The score has no memory of any other period — it’s recomputed fresh from whichever date range the analysis was run over, so the same portfolio will score differently across different windows purely because the assets’ realised correlation differed in each window (see the callout above).',
    whereItAppears: '`Dashboard` (**Diversification** metric card, second row).',
  },
  {
    id: 'correlation-matrix',
    index: '12',
    label: 'Correlation',
    heading: 'Correlation matrix',
    standard: 'ρ(X, Y) = Cov(X, Y) / (σ_X σ_Y)     (Pearson correlation coefficient)',
    standardNote: 'The standard linear-correlation measure, bounded [−1, +1]. Pearson’s ρ is the default, near-universal choice for a correlation matrix in this context; it does not capture non-linear or tail-dependence structure, which is a property of the method itself rather than anything Varense does differently.',
    implementation: 'corr = returns.corr()',
    implementationNote: 'A direct call to pandas’ `.corr()` on the daily return DataFrame, which computes Pearson correlation by default. No divergence, no parameters overridden. This same matrix is the sole input to the diversification score above.',
    whereItAppears: '`Risk Analysis` tab (**Correlation Matrix** panel, auto-scales for 3–5 tickers).',
  },
  {
    id: 'rolling-metrics',
    index: '13',
    label: 'Rolling',
    heading: 'Rolling volatility and rolling Sharpe',
    standard: 'Volatility and Sharpe recomputed on a trailing N-day sliding window rather than once over the full period, to show how risk and risk-adjusted performance evolved over time.',
    standardNote: 'No single "standard" window length exists in the literature — 30, 60, and 90 trading days are all common practitioner choices depending on how reactive vs. smooth the signal needs to be.',
    implementation: 'rolling_vol = portfolio_returns.rolling(window).std() * sqrt(252)\ndaily_rf = 0.045 / 252\nexcess = portfolio_returns - daily_rf\nrolling_sharpe = excess.rolling(window).mean() / excess.rolling(window).std() * sqrt(252)',
    implementationNote: 'Window defaults to 30 trading days (`compute_all_metrics(rolling_window=30)`), user-adjustable to 20 / 60 / 90 via the Risk Analysis tab’s Risk Window selector, which is passed straight through as the `rolling_window` field on the `/api/analyse` request. The risk-free rate is pro-rated to a daily figure by simple division (`0.045 / 252`, not compounded) before being subtracted from daily returns — a standard, common simplification for a rolling daily figure. Both rolling series annualise via the same √252 scaling used elsewhere in the codebase for daily-frequency figures. No meaningful divergence from how a rolling window is conventionally computed.',
    whereItAppears: '`Risk Analysis` tab (**Rolling Volatility** and **Rolling Sharpe** charts).',
  },
  {
    id: 'monte-carlo',
    index: '14',
    label: 'Monte Carlo',
    heading: 'Monte Carlo simulation',
    standard: 'Simulate N possible future price paths by drawing random daily returns from an assumed distribution and compounding them forward — the informative version accounts for cross-asset correlation (e.g. via a Cholesky-factored multivariate normal or full GBM); the naive version treats each asset’s daily return, or the portfolio’s own return, as independently and identically drawn from a single univariate distribution.',
    standardNote: 'Ignoring correlation between assets is the single most common way a Monte Carlo simulation understates real portfolio tail risk — assets that actually fall together get modelled as independent, which flatters the simulated distribution’s tails.',
    implementation: 'cov_daily = asset_returns.cov().values\nL = np.linalg.cholesky(cov_daily)\nZ = np.random.standard_normal((n_simulations, n_assets))\nday_asset_rets = daily_mean_vec + Z @ L.T\nday_port_rets = day_asset_rets @ weights',
    implementationNote: '1,000 simulated paths over a 252-trading-day (1yr) horizon, per run. The daily covariance matrix of the requested tickers is Cholesky-decomposed (`L`), and standard-normal draws are multiplied through `L.T` before being added to each asset’s historical mean daily return — this is what makes each simulated day’s asset returns carry the real historical correlation structure rather than being drawn independently. If the covariance matrix isn’t positive-definite, `numpy.linalg.cholesky` raises `LinAlgError`, and the code falls back to drawing the **portfolio’s own** historical daily returns from a single univariate normal (mean and std of `portfolio_returns`, not per-asset) — losing the correlation structure for that run, but still producing a result rather than failing the request. The response includes which path was taken (`method: "cholesky"` or `"fallback_univariate"`), though the frontend doesn’t currently display this. Three scenarios are run per analysis — bear (−10%/yr drift shift), base (historical drift, unchanged), bull (+10%/yr drift shift) — the shift is added on top of each asset’s own historical mean daily return, not substituted for it.',
    whereItAppears: '`Monte Carlo` tab (bear / base / bull toggle, percentile bands, probability of profit) and the median-outcome figure referenced in `Dashboard`’s Return insight box.',
  },
  {
    id: 'efficient-frontier',
    index: '15',
    label: 'Frontier',
    heading: 'Efficient frontier',
    standard: 'Markowitz mean-variance optimisation: solve a constrained quadratic program to find, for every achievable level of risk, the portfolio weights that maximise expected return (or equivalently, minimise variance for each target return) — the resulting curve is the efficient frontier, and it has a closed-form / convex-optimisation solution given the covariance matrix and expected returns.',
    standardNote: 'The frontier itself, and the maximum-Sharpe and minimum-volatility portfolios on it, are normally found analytically or via convex optimisation — not by sampling random portfolios and picking the best of the sample.',
    implementation: 'raw_weights = np.random.random((5000, n_assets))\nall_weights = raw_weights / raw_weights.sum(axis=1, keepdims=True)\n# ... compute return & vol for all 5,000, then:\nmax_sharpe_idx = argmax(all_sharpes)\nmin_vol_idx = argmin(all_vols)',
    implementationNote: 'This is the most significant divergence on this page, and the docstring says so directly: `compute_efficient_frontier` is explicitly "Markowitz Efficient Frontier via Monte Carlo simulation," not a solved quadratic program. It generates 5,000 random weight vectors (each of `n_assets` independent Uniform(0,1) draws, normalised to sum to 1 — a simple, fast approximation to a random simplex sample; it isn’t a true uniform-on-the-simplex distribution, which would require a Dirichlet(1,…,1) draw instead, and skews these samples slightly toward the equal-weight centre relative to that), computes CAGR return, annualised volatility, and Sharpe for every one of them, and reports the best Sharpe and lowest volatility **found among the 5,000 samples** as "optimal" — not the true analytical optimum. For a small number of assets (Varense caps portfolios at 5 tickers) and 5,000 samples, the sampled cloud is generally dense enough to sit very close to the true frontier, but it is an approximation of it, not the frontier itself. The return axis uses the identical CAGR formula as `compute_annualised_return` (see the callout above) specifically so the user’s actual portfolio plots consistently against the simulated cloud.',
    whereItAppears: '`Efficient Frontier` tab — the scatter of 5,000 simulated portfolios, the max-Sharpe and min-volatility markers, and "Your Portfolio"’s own position on the same axes.',
  },
  {
    id: 'stress-testing',
    index: '16',
    label: 'Stress test',
    heading: 'Historical stress testing',
    standard: 'Apply current portfolio weights to a historical crisis window’s actual realised returns, to see what the current portfolio would have lost had it existed through a past crisis — a standard scenario-analysis technique, distinct from Monte Carlo (it uses one realised historical path, not simulated ones).',
    standardNote: 'No single standard set of crisis windows exists — which historical periods to test is a judgment call every implementation makes.',
    implementation: 'STRESS_SCENARIOS = [\n  {"2008 Financial Crisis", "2008-09-01", "2009-03-31"},\n  {"COVID Crash", "2020-02-01", "2020-03-31"},\n  {"2022 Rate Shock", "2022-01-01", "2022-12-31"},\n]',
    implementationNote: 'Three fixed historical windows, hardcoded in `api.py`. For each, current portfolio weights are applied to that window’s actual realised returns to get the crisis-period portfolio return and worst single day. A ticker with fewer than 2 valid data points in the crash window (e.g. it hadn’t IPO’d yet) is dropped from that scenario and the remaining weights are renormalised to sum to 1 among the tickers that do have data — the dropped weight is not redistributed to cash, it simply isn’t represented in that scenario’s result, and is reported back as `excluded_tickers`. Recovery time is then searched for separately: prices are fetched forward up to 5 years past the crash start (capped at today), and `recovery_days` counts trading days from the crash-window trough until wealth first climbs back to its pre-crash peak — if it never does within that extended window, `recovery_days` is `null`. One gap worth naming here: `/api/stress-test` fetches this extended price window fresh on every call — it doesn’t currently go through the same 24-hour Redis cache that the main analysis and backtest paths use.',
    whereItAppears: '`Risk Analysis` tab (**Stress Test** panel).',
  },
  {
    id: 'backtesting',
    index: '17',
    label: 'Backtest',
    heading: 'Backtesting',
    standard: 'Run a strategy’s fixed weights forward through historical data and report cumulative return, volatility, Sharpe, and drawdown — standard practice, though "backtest" in the wider industry often implies an out-of-sample period distinct from whatever data informed the strategy’s construction.',
    standardNote: 'How rigorously in-sample/out-of-sample separation is enforced varies enormously by context — this is a property of how a backtest is used, not a fixed part of the term’s definition.',
    implementation: 'your_returns = returns.dot(weights)\nequal_returns = returns.dot([1/n]*n)\n# aligned to common trading days across all three, then per-strategy:\ncumulative, annualised_return, sharpe, max_drawdown, annual_returns',
    implementationNote: 'Three fixed-weight strategies — the user’s actual weights, an equal split across the same tickers, and the S&P 500 — are run through the **same single historical window** as the rest of the analysis (`start_date` to `end_date`), aligned to their common trading days, and each gets the same suite of stats (cumulative return series, CAGR, annualised volatility, Sharpe, max drawdown, plus a per-calendar-year return breakdown). This is a direct, transparent comparison of three fixed allocations over one realised history — it is not an out-of-sample test in the sense of validating a strategy that was fit on different data; the weights are simply whatever the user chose, run through the one period requested.',
    whereItAppears: '`Backtest` tab (cumulative return chart, year-by-year table, and the three-way comparison against Equal Weight and S&P 500).',
  },
]
